### ISSUE TITLE
How to remove horizontal lines ?

### ISSUE THREAD

**Issue by Offirmo** [tecfu/tty-table#10]
I want a more compact display, by removing horizontal lines between data lines (ok to keep it in header)

How can I do it ?

**Comment by tecfu** [comment]
You can do so by setting the configuration option "compact" to true. For example:

```
var t1 = Table(header,rows,footer,{
	borderStyle : 1,
	borderColor : "blue",
	paddingBottom : 0,
	headerAlign : "center",
	align : "center",
	color : "white",
	compact : true
});

str1 = t1.render();
console.log(str1);

```

**Comment by Offirmo** [comment]
This is great ! But I didn't see this option in the doc. Maybe should it be documented ?

**Comment by tecfu** [comment]
Added docs with https://github.com/tecfu/tty-table/commit/5d86a8b08bc31bb760065968213e48471384edad. Good catch!
