### ISSUE TITLE
Double-width East Asian characters vs other unicode characters

### ISSUE THREAD

**Issue by kac-** [tecfu/tty-table#11]
Hi,
Using Polish characters( like *ą,ć,ę* etc) cause layout breakage.
Output from `echo -e "abc\nabć\nab한" | ./node_modules/.bin/tty-table` is on [this screenshot](https://i.imgur.com/CdUaLhg.png).
[Format.calculateLength](https://github.com/tecfu/tty-table/blob/master/src/format.js#L5) assumes all unicode chars to be two-char width on display which isn't true.
Imo correct way to implement it is to (re)use method from [npm east-asian-width](https://www.npmjs.com/package/east-asian-width)( see also **links** section at the bottom of project's page).
Cheers

**Comment by kac-** [comment]
You can also use [npm wcwidth](https://www.npmjs.com/package/wcwidth).

**Comment by tecfu** [comment]
Thanks for your excellent feedback and for suggesting the solution within your issue request.

**Comment by kac-** [comment]
It looks fine now, `echo -e "abc\nĄĄĄĄ ęęęę ÓÓÓÓ\n한한 한한 한한" | node ./src/main.js` gives [screenshot](https://i.imgur.com/py6nhIc.png).
*Note: no wcwidth in package.json*

**Comment by tecfu** [comment]
@kac I remember now that I discovered about a year ago that [wcwidth](https://www.npmjs.com/package/wcwidth) causes my tests to fail on Centos see [job #162.1](https://travis-ci.org/tecfu/tty-table/jobs/176894873), which is why I hadn't used it previously. 

I committed to the master prior to seeing that with the CI build  - mistake. I'll need to find another workaround when I have a little time.

**Comment by kac-** [comment]
@tecfu I'm *grunt noob* so I cannot say why `grunt is not defined` but when I add *wcwidth* to *tty-table* using `npm install --save wcwidth` those errors are gone and all tests are passing.

**Comment by kac-** [comment]
https://travis-ci.org/kac-/tty-table/builds/177226040

**Comment by tecfu** [comment]
Merged your commit 72bd1da8. Tests pass. Good catch, thanks!

**Comment by tecfu** [comment]
Note that you didn't get credited as a contributor because the email address associated with your git repo evidently didn't match Github's database?

**Comment by kac-** [comment]
Ah, thanks for that, fixed. Also, thanks for maintaining this useful project.

**Comment by tecfu** [comment]
Sure thing. Hope you continue to find it useful in the future. Thanks again for putting so much effort into helping me out.
