### ISSUE TITLE
Pass styling when representing a JSON stream

### ISSUE THREAD

**Issue by BitterLox** [tecfu/tty-table#12]
I'm trying to represent a JSON stream, by piping my script with `| tty-table --format=json`
However the table is too little for it and it's not being visualized properly. Can i pass styling to it?

<img width="609" alt="schermata 2016-11-28 alle 18 45 30" src="https://cloud.githubusercontent.com/assets/12779177/20679368/e4272d16-b59a-11e6-9976-f4991de4f352.png">

Also, it would seem that when the table has more than two rows it bugs out? Or am i doing something wrong?

<img width="593" alt="schermata 2016-11-28 alle 19 22 02" src="https://cloud.githubusercontent.com/assets/12779177/20680594/fdcb6ab6-b59f-11e6-9364-2c738870a13f.png">

**Comment by tecfu** [comment]
You can now specify a file that contains the header configuration for a table like so:

```bash
node examples/data/fake-stream.js | tty-table --format json --header examples/config/header.js
```

header.js
```js
let chalk = require("chalk")
module.exports = [
  {
    "value": "ticker",
    "color": "cyan"
  },
  {
    "value": "last",
    "color": "red",
    width : 10,
    formatter : function(value){
      var str = "$" + value.toFixed(2);
      if(value > 130){
        str = chalk.bold.green(str);
      }
      return str;
    }
  }
]
```
