### ISSUE TITLE
asian character support?

### ISSUE THREAD

**Issue by stevenvachon** [tecfu/tty-table#2]
not that I need it, but I remember seeing issues regarding it posted for cli-table

**Comment by tecfu** [comment]
Since I don't need it and you are the only other person who has noted the package so far - I'll hold off for now. Its a good suggestion. Thank you.

**Comment by stevenvachon** [comment]
It seems pretty easy to replicate https://github.com/Automattic/cli-table/pull/67/files

**Comment by tecfu** [comment]
Fixed by https://github.com/tecfu/tty-table/pull/5. 

Thanks again @magicismight.
