### ISSUE TITLE
Example code throws 'undefined'

### ISSUE THREAD

**Issue by nstansbury** [tecfu/tty-table#23]
Running code in examples/data/fake-stream.js with  `node process_name | tty-table --format=json`

Output via `console.log(JSON.stringify(array))`

Throws `undefined`

Node v8.1.4

**Comment by tecfu** [comment]
I'm not quite sure what you're doing here. 

```

**Comment by nstansbury** [comment]
So how does my node process send data to stdout to be piped to tty-table, and how does tty-table read data piped to it from the output of my process?

**Comment by nstansbury** [comment]
You might like to look at the code in: https://github.com/tecfu/tty-table/blob/master/examples/data/streamer.js

**Comment by tecfu** [comment]
That streamer example basically just outputs a "stream" of data to STDOUT. You then pipe it to tty-table, which reads it from STDIN. Are you running an example verbatim and finding it doesn't work?

**Comment by nstansbury** [comment]
Yep I had realised what it was supposed to do.  I have a real-time stream of data I was trying use tty-table to chart, and couldn't get it to work, so I copied and pasted the code from fake-stream into my node process and got the error reported.

**Comment by tecfu** [comment]
If you run the examples given, do they work?
