### ISSUE TITLE
Error: Number of columns is inconsistent on line 363

### ISSUE THREAD

**Issue by junejie** [tecfu/tty-table#24]
I have csv file with line number of 365.

When i remove line 363. It still throw the error until my csv total line become 362.

I think the only line it can read is 363? 

Command i use to read is. 
cat filename.csv | tty-table

environment: osx 10.12.6
node: v6.10.3

**Comment by tecfu** [comment]
Perhaps you could attach your csv file and the code you're using to run it.

**Comment by junejie** [comment]
I cant find the file that I describe above, but please take a look of this file. This is similar issue.

[Uploading artifacts (2).zip…]()

**Comment by tecfu** [comment]
The link you included doesn't point to a file. If you're having trouble piping valid csv values, check that the values are valid using a linter like: https://csvlint.io/.

**Comment by junejie** [comment]
Hi, 

Thanks for the csvlink. I used it. It says that the csv is valid.
see: https://csvlint.io/validation/59ae44417b9ea00004000096

I reupload the csv file but renamed to .xlsx.
see: [price.xlsx](https://github.com/tecfu/tty-table/files/1276312/price.xlsx)
