### ISSUE TITLE
colorized only part of the line corrupt the table styling

### ISSUE THREAD

**Issue by GiladShoham** [tecfu/tty-table#26]
Here are the same 2 tables. 
The first one uses [chalk](https://www.npmjs.com/package/chalk) to colorized the deprecated in red.
As you can see the version column style / alignment is wrong.

![image](https://user-images.githubusercontent.com/3840769/32829798-d04b8474-c9fb-11e7-95d7-8e6181d8cdad.png)
![image](https://user-images.githubusercontent.com/3840769/32829807-da62fa5a-c9fb-11e7-8589-74a8867e44c1.png)

**Comment by tecfu** [comment]
Can you pleas paste/link your code?

**Comment by tecfu** [comment]
This probably has to do with ANSI escape sequences using square brackets.

**Comment by GiladShoham** [comment]
everything is ready here:
https://github.com/GiladShoham/tty-chalk-bug
