### ISSUE TITLE
Prevent truncating on specific cell

### ISSUE THREAD

**Issue by jonathanasquier** [tecfu/tty-table#27]
Hi, I'm using `truncate: "..."` and global parameter for my table and I'm trying to prevent truncation on a single cell. I Had no luck with `truncate: false` (default value) which sets the cell content to `"false"` (bug?)

Any idea?
Thanks!

**Comment by jonathanasquier** [comment]
up?

**Comment by tecfu** [comment]
Thanks for catching that "truncate: false" bug. I'll check it out when I have a chance, or you can send me a pull request. 

I haven't implemented truncation on a per cell basis, but again you could issue a pull request for it if you wanted.

**Comment by tecfu** [comment]
I checked 
```js
truncate: false
```

And that works fine. Perhaps what you where doing was passing false as a string? Its meant to be a boolean when the value is false. 

```js
truncate: "false"
```
This would have indeed truncated lines with the word "false".

---

I've added support for truncation with no added character in https://github.com/tecfu/tty-table/commit/7c03d1b2f047d3d60e35d51bf8dbb75109fa6c25.

**Comment by tecfu** [comment]
As of tty-table@4.1.0 you can set truncation on a cell-by-cell basis using the column formatter function. Here's an example:

```js
formatter: function (cellValue, columnIndex, rowIndex) {
  if (rowIndex === 1) {
    this.configure({ truncate: false })
  }
  return cellValue
}
```
This example would turn off truncation and wrap the text in the second row of the column the formatter function is associated with.
