### ISSUE TITLE
Nested tables

### ISSUE THREAD

**Issue by jonathanasquier** [tecfu/tty-table#28]
Hi, I tried to return a `table.render()` in a formatter function but broke everything.
Is nesting tables possible?
Am I missing something?

Thanks!

**Comment by jonathanasquier** [comment]
up?

**Comment by tecfu** [comment]
I haven't tried this, but it should work. 

- You'd pass the evaluated output of your nested table as a value in the parent table. Its just text. 
- You'd set alignment to left on parent table cells with nested tables 
- You'd need to turn truncation on and use an empty string. Something like:
```
truncate: " "
```

This program is really designed to be responsive and to automatically wrap cell values if the table is too wide for the terminal. I don't think it would be too much work to create a "nested mode", but I haven't really got time at the moment. 

If you want to issue a pull request and include some tests I'll bundle it with the next release.
