### ISSUE TITLE
Vertical table support

### ISSUE THREAD

**Issue by petersandor** [tecfu/tty-table#3]
Are vertical tables supported? If yes, example should be added to documentation, since it
s not quite clear for new user like me. Thanks.

**Comment by tecfu** [comment]
Not supported. Current documentation covers all functionality.

**Comment by tecfu** [comment]
Great idea. Feel free to send me a pull request. I'd be happy to merge that feature.

**Comment by tecfu** [comment]
This is now supported via the [Automattic/cli-table adapter. Docs available here](https://github.com/tecfu/tty-table/blob/master/docs/automattic-cli-table.md).
