### ISSUE TITLE
Incorrect number of columns

### ISSUE THREAD

**Issue by deftomat** [tecfu/tty-table#31]
# Problem Summary
Version **2.5.6** introduce the following issue: It is not possible to have multiple tables with a different number of columns. Version _2.5.5_. is ok. 

Consider this code:
```ts
import table from 'tty-table';

const header = [
  { value: 'col1' },
  { value: 'col2' }
];

const rows = [[1, 2]];
console.log(table(header, rows).render());

const header2 = [
  { value: 'col1' },
  { value: 'col2' },
  { value: 'col3' }
];

const rows2 = [[1, 2, 3]];
console.log(table(header2, rows2).render());
```

## Expected Result
![image](https://user-images.githubusercontent.com/5549148/37333579-fe913634-26a9-11e8-90b7-069cf3622972.png)

## Actual Result
![image](https://user-images.githubusercontent.com/5549148/37333553-ea8fdf6e-26a9-11e8-9aa5-efb8415d2cc6.png)

## Environment Information 

 * OS: macOS High Sierra
 * Terminal: iTerm2

**Comment by jonathanasquier** [comment]
Got this one too +1

**Comment by reflexdemon** [comment]
I too have the same issue... +1

**Comment by deftomat** [comment]
@tecfu Thanks 👍

**Comment by tecfu** [comment]
@deftomat No problem. Thank you.
