### ISSUE TITLE
Disable strict mode

### ISSUE THREAD

**Issue by harshitgupta** [tecfu/tty-table#32]
# Problem Summary
Short: Seems like `tty-table` is making the host use strict mode because of which my system is failing to make web pack build. 

Detailed: my gulp task has dependency on 'css-loader' which is also using `tty-table`. `css-loader` relies on `cssnano`, which relies on `postcss-filter-plugins`, which relies on `uniqid`, which relies on `macaddress`. `macaddress` has a global leak in v0.2.8 but it has been fixed in v0.2.9 but `uniqid` hasn't updated its dependency version for `macaddress`.

## Environment Information 

 * OS: macOX Sierra

 * Terminal Emulator: Terminal

## Steps to Reproduce 
 1. Just import the `uniqid` and `tty-table` modules in same project.

<img width="892" alt="screen shot 2018-04-23 at 5 14 23 pm" src="https://user-images.githubusercontent.com/1644577/39155948-cfc1c37e-4719-11e8-9ee9-ee60ce273a40.png">

**Comment by harshitgupta** [comment]
appreciate the quick resolution.

**Comment by tecfu** [comment]
No problem. Good luck with your project.
