### ISSUE TITLE
ignore excessive newlines 

### ISSUE THREAD

**Issue by sourcevault** [tecfu/tty-table#37]
It it possible to get rid of excess new lines at the beginning of the table ? and around the heading ?

<img width="264" alt="untitled" src="https://user-images.githubusercontent.com/20347647/42715940-ffdf65e8-871a-11e8-8d06-a64b7f419972.png">

Also how to disable colors for the heading ?

 * OS: Windows 10 (Creator's Update)

 * Terminal Emulator: ConEmu

Thanks

**Comment by tecfu** [comment]
Can you post your code for me?

**Comment by tecfu** [comment]
Here's the output I get on Windows 10 with a fresh install of ConEmu.

![conemu-screenshot](https://user-images.githubusercontent.com/7478359/42721160-9080e4ea-86ea-11e8-8125-333385185a18.png)

 This is consistent with what I expect. Here's the code I used:

```
var Table = require('../');
var chalk = require('chalk');

var header = [
  {
    alias: "line number",
    width: 10
  },
  {
    alias: "path"
  },
];

//Example with arrays as rows 
var rows = [
  [4,".\\test.js"],
  [40,".\\main.js"],
];

var t1 = Table(header,rows,{
  borderColor : "",
  paddingBottom : 0,
  headerAlign : "center",
  align : "center",
  color : "white",
});

str1 = t1.render();
console.log(str1);
```

I did notice, however, that command line calls to tty-table hang after a global install on npm. I'm not a Windows user primarily and I don't know that anyone is using tty-table this way, so I'm going to ignore that issue for now unless someone sends me a PR. 

Let me know if this doesn't fix your problem.

**Comment by sourcevault** [comment]
Hey @tecfu  Thank you for the quick reply.

I looked at your code and found `marginTop` which helped to reduce one `\n` but there is still one extra `\n` that I am unable to get rid of - I think its hardcoded ( not sure ).

for now I am going to use a hackish solution that removes the first line :

```livescript
table.render! |> _.split "\n" |> _.drop 1 |> _.join "\n" 
```
I like everything about `tty-table` except this single issue.

Cheers !

**Comment by tecfu** [comment]
Thanks for your feedback. My memory is shot, i guess. I completely forgot that I fixed this long ago. 

The reason for the margin on the top is because I wanted to make the unit tests pass the test suite for automattic/cli-table so that I could prove backwards compatibility. 

Anyway, to solve this problem that you can just pass `marginTop: 0` as an option as shown below:

```
var Table = require('../');

var header = [
  {
    alias: "line number",
    width: 10
  },
  {
    alias: "path"
  },
];

//Example with arrays as rows 
var rows = [
  [4,".\\test.js"],
  [40,".\\main.js"],
];

var t1 = Table(header,rows,{
  marginTop: 0,
});

str1 = t1.render();
console.log(str1);
```
![conemu-screenshot](https://user-images.githubusercontent.com/7478359/42725717-5deee34e-873d-11e8-934e-6cae853a26de.png)

**Comment by sourcevault** [comment]
Thanks
