### ISSUE TITLE
Options 'truncate' doesn't play well with Chinese

### ISSUE THREAD

**Issue by Styx11** [tecfu/tty-table#43]
Hi, I've been using this package recently, and I have to say it's an excellent package. 

But I have a bit of a problem with the 'truncate' option:
```
const table = table (header, rows, {
  truncate: '... '
});
```
I've defined a 'table' object, but it doesn't seem to work properly with truncation issues like Chinese

e.g

![](https://s2.ax1x.com/2019/11/11/MlkS7n.png)

As you can see it's not truncated correctly

Thank you very much if you can repair it in time

**Comment by tecfu** [comment]
Can you please paste your code so that I can reproduce?

**Comment by tecfu** [comment]
Also, can you please make sure you are using the latest version?

**Comment by tecfu** [comment]
Thanks for creating this ticket. Please let me know if you have any other issues!

**Comment by Styx11** [comment]
Oh, the problem has been solved.

Because the CNPM download source did not download the latest package, I thought it was the latest.

Thank you for your time🥴
