### ISSUE TITLE
rendering issue if truncate is true and first header cell needs truncation

### ISSUE THREAD

**Issue by mscalora** [tecfu/tty-table#49]
# Problem Summary

rendering issue if truncate is true and first header cell needs truncation

Change examples/truncated-lines.js line 6 to:

    value: "item name",

## Expected Result (screen shot if possible)

Table 3 of :

    ┌──────────┬──────────┬──────────┐
    │ item nam │  price   │ organic  │
    ├──────────┼──────────┼──────────┤
    │ chocolat │   5.65   │    no    │
    └──────────┴──────────┴──────────┘

## Actual Result (screen shot if possible)

      ┌──────────┬──────────┬──────────┐
      │item nametrue│  price   │ organic  │
      ├──────────┼──────────┼──────────┤
      │ chocolat │   5.65   │    no    │
      └──────────┴──────────┴──────────┘

## Environment Information 

 * OS: Mac OS

 * Terminal Emulator: iTerm

## Steps to Reproduce 

 1. Change examples/truncated-lines.js line 6 to: `value: "item name",`
 2. Run examples/truncated-lines.js

## Cause

`Format.wrapCellContent` mutates `truncate` values of true in config *after* the very first cell's `cellOptions` have been created, `Format.handleTruncatedValue` uses the untranslated `truncate` value as if it is always a string.

## Fix

See pull request #48

**Comment by tecfu** [comment]
Great job. Thanks.
