### ISSUE TITLE
Embedded ansi

### ISSUE THREAD

**Issue by mscalora** [tecfu/tty-table#56]
# Problem Summary

Embedded ansi styling causes problems with column widths and line breaking doesn't work correctly.

## Expected Result (screen shot if possible)

- Columns should be sized to the text
- Styling should be contained within cells and not bleed over into borders and other cells

## Actual Result (screen shot if possible)

Columns are sized wrong and styling bleeds across lines and out of cells

## Environment Information 

 * OS: MacOS

 * Terminal Emulator: iTerm

## Steps to Reproduce 

run:
```
    const example = require("../test/example-utils.js"),
      kleur = require("kleur"),
      Table = require("../")
    
    const rows1 = [
        ["plain test", `one ${kleur.red("red")} word`, `some ${kleur.bold("bold")} and ${kleur.dim("dim")} words`]
      ],
      rows2 = [
        ["plain test", `a ${kleur.red("few red words in")} here`]
      ]
    
    function test(testName, tableWidth, rows, config) {
      console.log(`\n${kleur.cyan(testName)}`)
      example.init(`Test: ${testName}`, tableWidth)
      let table = new Table(rows, config),
        output = table.render()
    
      console.log(output)
      console.log("")
    }
    
    test("Embedded ansi column width", 100, rows1, {})
    
    test("Embedded ansi breaking", 20, rows2, {})
```

**Comment by tecfu** [comment]
@mscalora Thanks for reporting! This was a tough fix, and there are some trade-offs involved. 

The only way to preserve ANSI escape codes across multi line strings is to escape each character individually. I haven't seen anyone else do this, and I know none of the other tables carry support for that feature. It's quite a bit slower to do this. 

I've also added some convenience methods `style` and `resetStyle` to the import function, but I haven't documented them yet because I haven't tested edge cases.

**Comment by tecfu** [comment]
For the example given, you'll want to use the "style" convenience method like so: 

```js
const example = require("../test/example-utils.js"),
      Table = require("../"),
      style = Table.style
    
    const rows1 = [
        ["plain test", `one ${style("red", "red")} word`, `some ${style("bold", "bold")} and ${style("dim", "dim")} words`]
      ],
      rows2 = [
        ["plain test", `a ${style("few red words in", "red")} here`]
      ]
    
    function test(testName, tableWidth, rows, config) {
      console.log(`\n${style(testName, "cyan")}`)
      example.init(`Test: ${testName}`, tableWidth)
      let table = new Table(rows, config),
        output = table.render()
    
      console.log(output)
      console.log("")
    }
    
    test("Embedded ansi column width", 70, rows1, {})
    
    test("Embedded ansi breaking", 20, rows2, {})
```
