### ISSUE TITLE
npm test OR node examples/cli-test.js fails

### ISSUE THREAD

**Issue by mscalora** [tecfu/tty-table#58]
# Problem Summary

tests are broken

## Expected Result (screen shot if possible)

pass

## Actual Result (screen shot if possible)

errors on every test

## Environment Information 

 * OS: Mac

 * Terminal Emulator: iTerm

## Steps to Reproduce 

1. git clone git@github.com:tecfu/tty-table.git
2. cd tty-table
3. npm install
4. npm test
 
Maybe smartwrap dependency is out of date?

when:
   node examples/cli-test.js                                                                                                                                                      

I get:
...tty-table/node_modules/smartwrap/src/main.js:286
  return processedLines.flat(2).join("\n")
TypeError: processedLines.flat is not a function

**Comment by tecfu** [comment]
The required node version was increased to 11 on tty-table > 3.0.0. 
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

You can upgrade node or downgrade to the 2.x branch to resolve.
