### ISSUE TITLE
Support for Table Footers?

### ISSUE THREAD

**Issue by sayanriju** [tecfu/tty-table#6]
Similar to how we can provide table headers perhaps?

I need it for providing "column totals" at the bottom.

**Comment by tecfu** [comment]
Great idea. Feel free to send me a pull request. I'd be happy to merge that feature.

**Comment by tecfu** [comment]
Feature has been added. Closed by commit https://github.com/tecfu/tty-table/commit/736c44589173c21807fa002383eb3c950bff3ef7. 

Thanks for the suggestion.
