### ISSUE TITLE
Using a falsy value like 0 in a cell displays nothing

### ISSUE THREAD

**Issue by jonathanasquier** [tecfu/tty-table#71]
# Problem Summary

Using a falsy value like 0 in a cell displays nothing

## Expected Result (screen shot if possible)

![2020-12-06-194202_479x197_scrot](https://user-images.githubusercontent.com/781447/101289174-201ca800-37fb-11eb-887b-b906081beacf.png)

## Actual Result (screen shot if possible)

![2020-12-06-194112_493x211_scrot](https://user-images.githubusercontent.com/781447/101289156-04b19d00-37fb-11eb-8329-432de171e458.png)

## Environment Information 

 * OS: Ubuntu 20.04.1 LTS

 * Terminal Emulator: gnome terminal

 * Node Version: 12

## Steps to Reproduce 

- Set a cell to 0
- render

**Comment by tecfu** [comment]
Thanks for reporting. Feel free to send me in a PR, otherwise it will be a little while before I get to this.
