### ISSUE TITLE
Smartwrap deprecation warning

### ISSUE THREAD

**Issue by vhscom** [tecfu/tty-table#88]
# Problem Summary

Projects using tty-table such as the popular changesets cli output deprecation warning related to smartwrap:

![Screenshot from 2022-02-16 14-23-43](https://user-images.githubusercontent.com/97140109/154208204-ef9b8095-4a2b-462c-933d-44fdb9eadb6c.png)

## Expected Result (screen shot if possible)

No deprecation warning

## Actual Result (screen shot if possible)

See screenshot above.

## Environment Information 

 * OS: GNU/Linux 5.15.11-3-t2

 * Terminal Emulator: Alacritty

 * Node Version: 17.x

## Steps to Reproduce 

 1. Clone https://codeberg.org/vhs/oathqr
 2. Install dependencies with `pnpm i`
 3. Run `pnpm up` to observe warning message

**Comment by tecfu** [comment]
Hi @vhscom. Is there any reason in particular that you are still running the 2.x release of tty-table? I deprecated @tecfu/smartwrap some time ago to push users to upgrade.

![image](https://user-images.githubusercontent.com/7478359/173002897-16ffeabc-2980-4cc8-9d9a-5e466c658fa3.png)

**Comment by vhscom** [comment]
> I deprecated @tecfu/smartwrap some time ago to push users to upgrade.

Ah got it. Thanks for the clarification @tecfu. It wasn't clear to me what the deprecation message was trying to get across as it was coming across out of context. Upgrade it is.

**Comment by tecfu** [comment]
Awesome, thanks for using the tool and participating in development. Hope it does what you need.

**Comment by vhscom** [comment]
>  I deprecated @tecfu/smartwrap some time ago to push users to upgrade.

Ah got it. Thanks for the clarification @tecfu. It wasn't clear to me what the deprecation message was trying to get across as it was coming across out of context. And the suggestion is for dependents to upgrade.
