### ISSUE TITLE
Support truncation like automattic-cli-table

### ISSUE THREAD

**Issue by arunasank** [tecfu/tty-table#9]
Support a truncation option like in https://github.com/Automattic/cli-table/blob/b44c0c335e396121a2a049b3d9fa9eaf9b3571f8/lib/index.js#L38

**Comment by tecfu** [comment]
Fixed by https://github.com/tecfu/tty-table/commit/596b6b9b8aeb0892ddb92bddef7988194d29ef8f. Thanks for your recommendation.
