### ISSUE TITLE
footerColor is missing from Options

### ISSUE THREAD

**Issue by erakis** [tecfu/tty-table#98]
# Problem Summary

## Expected Result (screen shot if possible)

```typescript
  export interface Options {
    borderStyle?: string;
    borderColor?: string;
    color?: string;
    compact?: boolean;
    defaultErrorValue?: string;
    defaultValue?: string;
    errorOnNull?: boolean;
    truncate?: string | boolean;
    width?: string;
    footerColor?: string;  // HERE
  }
```

## Actual Result (screen shot if possible)

![image](https://github.com/tecfu/tty-table/assets/7946730/7f49dfde-570a-4229-9449-b4101ee17356)

## Environment Information 

 * OS: Windows 10

 * Terminal Emulator:

 * Node Version: 18 (Typescript)

 * tty-table version: 4.2.1

## Steps to Reproduce 

```typescript
  const table = Table(tableHeaders, tableRows, tableFooter, {
    footerColor: 'red',
  });
```

**Comment by tecfu** [comment]
Fixed in version [4.2.3](https://www.npmjs.com/package/tty-table/v/4.2.3).
